name: package_demo

description: A simple app to display products and their attributes.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.4.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.1
  build_runner: ^2.2.0
  json_serializable: ^6.1.5
